package main

import (
    "fmt"
)

type Kana struct {
    word_map map[string]string
    spell_map map[string]string
}

func create_kana() *Kana {
    return &Kana{word_map: make(map[string]string), spell_map: make(map[string]string)}
}

func add_kana(k *Kana, word string, spell string) {
    k.word_map[word] = spell
    k.spell_map[spell] = word
}

func init_hiragana(hiragana* Kana) *Kana {
    add_kana(hiragana, "あ", "a")
    add_kana(hiragana, "い", "i")
    add_kana(hiragana, "う", "u")
    add_kana(hiragana, "え", "e")
    add_kana(hiragana, "お", "o")
    add_kana(hiragana, "か", "ka")
    add_kana(hiragana, "き", "ki")
    add_kana(hiragana, "く", "ku")
    add_kana(hiragana, "け", "ke")
    add_kana(hiragana, "こ", "ko")
    add_kana(hiragana, "さ", "sa")
    add_kana(hiragana, "し", "shi")
    add_kana(hiragana, "す", "su")
    add_kana(hiragana, "せ", "se")
    add_kana(hiragana, "そ", "so")
    add_kana(hiragana, "な", "na")
    add_kana(hiragana, "に", "ni")
    add_kana(hiragana, "ぬ", "nu")
    add_kana(hiragana, "ね", "ne")
    add_kana(hiragana, "の", "no")
    add_kana(hiragana, "は", "ha")
    add_kana(hiragana, "ひ", "hi")
    add_kana(hiragana, "ふ", "fu")
    add_kana(hiragana, "へ", "he")
    add_kana(hiragana, "ほ", "ho")
    add_kana(hiragana, "ま", "ma")
    add_kana(hiragana, "み", "mi")
    add_kana(hiragana, "む", "mu")
    add_kana(hiragana, "め", "me")
    add_kana(hiragana, "も", "mo")
    add_kana(hiragana, "や", "ya")
    add_kana(hiragana, "ゆ", "yu")
    add_kana(hiragana, "よ", "yo")
    add_kana(hiragana, "ら", "ra")
    add_kana(hiragana, "り", "ri")
    add_kana(hiragana, "る", "ru")
    add_kana(hiragana, "れ", "re")
    add_kana(hiragana, "ろ", "ro")
    add_kana(hiragana, "わ", "wa")
    add_kana(hiragana, "ゐ", "wi")
    add_kana(hiragana, "ゑ", "we")
    add_kana(hiragana, "を", "wo")
    add_kana(hiragana, "ん", "n")
    add_kana(hiragana, "が", "ga")
    add_kana(hiragana, "ぎ", "gi")
    add_kana(hiragana, "ぐ", "gu")
    add_kana(hiragana, "げ", "ge")
    add_kana(hiragana, "ご", "go")
    add_kana(hiragana, "ざ", "za")
    add_kana(hiragana, "じ", "zi")
    add_kana(hiragana, "ず", "zu")
    add_kana(hiragana, "ぜ", "ze")
    add_kana(hiragana, "ぞ", "zo")
    add_kana(hiragana, "だ", "da")
    add_kana(hiragana, "ぢ", "ji")
    add_kana(hiragana, "づ", "zu")
    add_kana(hiragana, "で", "de")
    add_kana(hiragana, "ど", "do")
    add_kana(hiragana, "ば", "ba")
    add_kana(hiragana, "び", "bi")
    add_kana(hiragana, "ぶ", "bu")
    add_kana(hiragana, "べ", "be")
    add_kana(hiragana, "ぼ", "bo")
    add_kana(hiragana, "ぱ", "pa")
    add_kana(hiragana, "ぴ", "pi")
    add_kana(hiragana, "ぷ", "pu")
    add_kana(hiragana, "ぺ", "pe")
    add_kana(hiragana, "ぽ", "po")
    add_kana(hiragana, "っ", "*")
    add_kana(hiragana, "きゃ", "kya")
    add_kana(hiragana, "しゃ", "sha")
    add_kana(hiragana, "ちゃ", "cha")
    add_kana(hiragana, "にゃ", "nya")
    add_kana(hiragana, "ひゃ", "hya")
    add_kana(hiragana, "みゃ", "mya")
    add_kana(hiragana, "りゃ", "rya")
    add_kana(hiragana, "ぎゃ", "gya")
    add_kana(hiragana, "じゃ", "zya")
    add_kana(hiragana, "ぢゃ", "ja ")
    add_kana(hiragana, "びゃ", "bya")
    add_kana(hiragana, "ぴゃ", "pya")
    add_kana(hiragana, "きゅ", "kyu")
    add_kana(hiragana, "しゅ", "shu")
    add_kana(hiragana, "ちゅ", "chu")
    add_kana(hiragana, "にゅ", "nyu")
    add_kana(hiragana, "ひゅ", "hyu")
    add_kana(hiragana, "みゅ", "myu")
    add_kana(hiragana, "りゅ", "ryu")
    add_kana(hiragana, "ぎゅ", "gyu")
    add_kana(hiragana, "じゅ", "zyu")
    add_kana(hiragana, "ぢゅ", "ju")
    add_kana(hiragana, "びゅ", "byu")
    add_kana(hiragana, "ぴゅ", "pyu")
    add_kana(hiragana, "きょ", "kyo")
    add_kana(hiragana, "しょ", "sho")
    add_kana(hiragana, "ちょ", "cho")
    add_kana(hiragana, "にょ", "nyo")
    add_kana(hiragana, "ひょ", "hyo")
    add_kana(hiragana, "みょ", "myo")
    add_kana(hiragana, "りょ", "ryo")
    add_kana(hiragana, "ぎょ", "gyo")
    add_kana(hiragana, "じょ", "zyo")
    add_kana(hiragana, "ぢょ", "jo")
    add_kana(hiragana, "びょ", "byo")
    add_kana(hiragana, "ぴょ", "pyo")
    return hiragana
}

func init_katakana(katakana* Kana) *Kana {
    add_kana(katakana, "ア", "a")
    add_kana(katakana, "イ", "i")
    add_kana(katakana, "ウ", "u")
    add_kana(katakana, "エ", "e")
    add_kana(katakana, "オ", "o")
    add_kana(katakana, "カ", "ka")
    add_kana(katakana, "キ", "ki")
    add_kana(katakana, "ク", "ku")
    add_kana(katakana, "ケ", "ke")
    add_kana(katakana, "コ", "ko")
    add_kana(katakana, "サ", "sa")
    add_kana(katakana, "シ", "shi")
    add_kana(katakana, "ス", "su")
    add_kana(katakana, "セ", "se")
    add_kana(katakana, "ソ", "so")
    add_kana(katakana, "ナ", "na")
    add_kana(katakana, "ニ", "ni")
    add_kana(katakana, "ヌ", "nu")
    add_kana(katakana, "ネ", "ne")
    add_kana(katakana, "ノ", "no")
    add_kana(katakana, "ハ", "ha")
    add_kana(katakana, "ヒ", "hi")
    add_kana(katakana, "フ", "fu")
    add_kana(katakana, "ヘ", "he")
    add_kana(katakana, "ホ", "ho")
    add_kana(katakana, "マ", "ma")
    add_kana(katakana, "ミ", "mi")
    add_kana(katakana, "ム", "mu")
    add_kana(katakana, "メ", "me")
    add_kana(katakana, "モ", "mo")
    add_kana(katakana, "ヤ", "ya")
    add_kana(katakana, "ユ", "yu")
    add_kana(katakana, "ヨ", "yo")
    add_kana(katakana, "ラ", "ra")
    add_kana(katakana, "リ", "ri")
    add_kana(katakana, "ル", "ru")
    add_kana(katakana, "レ", "re")
    add_kana(katakana, "ロ", "ro")
    add_kana(katakana, "ワ", "wa")
    add_kana(katakana, "ヰ", "wi")
    add_kana(katakana, "ヱ", "we")
    add_kana(katakana, "ヲ", "wo")
    add_kana(katakana, "ン", "n")
    add_kana(katakana, "ガ", "ga")
    add_kana(katakana, "ギ", "gi")
    add_kana(katakana, "グ", "gu")
    add_kana(katakana, "ゲ", "ge")
    add_kana(katakana, "ゴ", "go")
    add_kana(katakana, "ザ", "za")
    add_kana(katakana, "ジ", "zi")
    add_kana(katakana, "ズ", "zu")
    add_kana(katakana, "ゼ", "ze")
    add_kana(katakana, "ゾ", "zo")
    add_kana(katakana, "ダ", "da")
    add_kana(katakana, "ヂ", "ji")
    add_kana(katakana, "ヅ", "zu")
    add_kana(katakana, "デ", "de")
    add_kana(katakana, "ド", "do")
    add_kana(katakana, "バ", "ba")
    add_kana(katakana, "ビ", "bi")
    add_kana(katakana, "ブ", "bu")
    add_kana(katakana, "ベ", "be")
    add_kana(katakana, "ボ", "bo")
    add_kana(katakana, "パ", "pa")
    add_kana(katakana, "ピ", "pi")
    add_kana(katakana, "プ", "pu")
    add_kana(katakana, "ペ", "pe")
    add_kana(katakana, "ポ", "po")
    add_kana(katakana, "ッ", "*")
    add_kana(katakana, "キャ", "kya")
    add_kana(katakana, "シャ", "sha")
    add_kana(katakana, "チャ", "cha")
    add_kana(katakana, "ニャ", "nya")
    add_kana(katakana, "ヒャ", "hya")
    add_kana(katakana, "ミャ", "mya")
    add_kana(katakana, "リャ", "rya")
    add_kana(katakana, "ギャ", "gya")
    add_kana(katakana, "ジャ", "zya")
    add_kana(katakana, "ヂャ", "ja")
    add_kana(katakana, "ビャ", "bya")
    add_kana(katakana, "ピャ", "pya")
    add_kana(katakana, "キュ", "kyu")
    add_kana(katakana, "シュ", "shu")
    add_kana(katakana, "チュ", "chu")
    add_kana(katakana, "ニュ", "nyu")
    add_kana(katakana, "ヒュ", "hyu")
    add_kana(katakana, "ミュ", "myu")
    add_kana(katakana, "リュ", "ryu")
    add_kana(katakana, "ギュ", "gyu")
    add_kana(katakana, "ジュ", "zyu")
    add_kana(katakana, "ヂュ", "ju")
    add_kana(katakana, "ビュ", "byu")
    add_kana(katakana, "ピュ", "pyu")
    add_kana(katakana, "キョ", "kyo")
    add_kana(katakana, "ショ", "sho")
    add_kana(katakana, "チョ", "cho")
    add_kana(katakana, "ニョ", "nyo")
    add_kana(katakana, "ヒョ", "hyo")
    add_kana(katakana, "ミョ", "myo")
    add_kana(katakana, "リョ", "ryo")
    add_kana(katakana, "ギョ", "gyo")
    add_kana(katakana, "ジョ", "zyo")
    add_kana(katakana, "ヂョ", "jo")
    add_kana(katakana, "ビョ", "byo")
    add_kana(katakana, "ピョ", "pyo")
    return katakana
}

var hiragana *Kana = create_kana()
var katakana *Kana = create_kana()

func main() {
    fmt.Println("Hello World.")

    init_hiragana(hiragana)
    fmt.Println(hiragana)

    init_katakana(katakana)
    fmt.Println(katakana)
}